[battery]
full_symbol = "ğŸ”‹"
charging_symbol = "âš¡ï¸"
discharging_symbol = "ğŸ’€"

[git_commit]
commit_hash_length = 8

[git_state]
progress_divider = " of "
cherry_pick = "ğŸ’ PICKING"

[directory]
truncation_length = 5
truncate_to_repo = true

[kubernetes]
symbol = "â˜¸ "
style = "bold blue"
disabled = false
[kubernetes.context_aliases]
"gke_vision-poc-285617_us-west1-a_vision-k8s-west" = "vision-west"
"gke_vision-poc-285617_us-east4-a_vision-k8s-east" = "vision-east"
"gke_iwcs-ai-dev_us-central1-b_tool-cluster-dev-central" = "ai"